### ISSUE TITLE
Test coverage timing issue

### ISSUE THREAD

**Issue by hueniverse** [hapijs/subtext#16]
Some lines are not always covered. Must be a timing issue with the tests.

```
59 tests complete
Test duration: 216 ms
Assertions count: 157 (verbosity: 2.66)
No global variable leaks detected
Coverage: 98.16% (6/326)
lib/index.js missing coverage on line(s): 365, 366, 368, 418, 419, 420
Code coverage below threshold: 98.16 < 100
Linting results: No issues
```

**Comment by johnbrett** [comment]
This is down to the `sudo: false` flag on travis. Investigating.

**Comment by hueniverse** [comment]
This happens on my local machine every 4-5 tries.

**Comment by johnbrett** [comment]
This is proving quite difficult to debug. It seems that Pez isn't always sending the 'close' event, or at least not in the right order of events. 

The following tests give inconsistent results over the course of a few runs:
````javascript
   it('parses a multipart file as file', function (done) {

        var path = Path.join(__dirname, './file/image.jpg');
        var stats = Fs.statSync(path);

        var form = new FormData();
        form.append('my_file', Fs.createReadStream(path));
        form.headers = form.getHeaders();

        Subtext.parse(form, null, { parse: true, output: 'file' }, function (err, parsed) {

            expect(err).to.not.exist();

            expect(parsed.payload.my_file.bytes).to.equal(stats.size);

            var sourceContents = Fs.readFileSync(path);
            var receivedContents = Fs.readFileSync(parsed.payload.my_file.path);
            Fs.unlinkSync(parsed.payload.my_file.path);
            expect(sourceContents).to.deep.equal(receivedContents);
            done();
        });
    });

    it('parses multiple files as files', function (done) {

        var path = Path.join(__dirname, './file/image.jpg');
        var stats = Fs.statSync(path);

        var form = new FormData();
        form.append('file1', Fs.createReadStream(path));
        form.append('file2', Fs.createReadStream(path));
        form.headers = form.getHeaders();

        Subtext.parse(form, null, { parse: true, output: 'file' }, function (err, parsed) {

            expect(err).to.not.exist();
            expect(parsed.payload.file1.bytes).to.equal(stats.size);
            expect(parsed.payload.file2.bytes).to.equal(stats.size);
            Fs.unlinkSync(parsed.payload.file1.path);
            Fs.unlinkSync(parsed.payload.file2.path);
            done();
        });
    });
````

Still investigating.

**Comment by johnbrett** [comment]
Ok there's a race condition causing the code coverage not to be 100%, there's no bugs to worry about, but it means execution order cannot be guaranteed making 100% code coverage pretty difficult.

Problem is in the lines below:
````javascript
var onPart = function (part) {
      
    if (self.settings.output === 'file') { // Output: 'file'
        var id = nextId++;
        pendingFiles[id] = true;
        self.writeFile(part, function (err, path, bytes) {

            delete pendingFiles[id]; // <- sometimes called before or after the 'onClose' event
            // ... rest of 'onPart' ...
}

var onClose = function () {
      
    if (Object.keys(pendingFiles).length) { // <- 0 or 1 depending on whether onClose event fired before writeFile finished
        closed = true;
        return;
    }

    // ... rest of 'onClose ..
}
````
Meaning for two possible flows *A*:
 - 'onPart' event
 - pendingFiles[id] = true;
 - self.writeFile(part, function (err, path, bytes) {
 - delete pendingFiles['id'];
 - 'onClose' event
 - if (Object.keys(pendingFiles).length) { // 0

*B* where *sometimes* the 'onClose' event fires before the self.writeFile callback is called, meaning:
 - 'onPart' event
 - pendingFiles[id] = true;
 - self.writeFile(part, function (err, path, bytes) {
 - 'onClose' event
 - if (Object.keys(pendingFiles).length) { ... } // This now becomes 1
 - delete pendingFiles['id'];
 
It seems the problematic test is 51: 'parses multiple files as files'. Sometimes it goes by flow A, making those lines in the travis test case not be covered. @hueniverse is there a way I can force event ordering here or do you know of a better approach?

**Comment by hueniverse** [comment]
Will different files sizes help? Maybe monkey patch some of the file APIs to make them produce different timing?

**Comment by johnbrett** [comment]
Added different file sizes & combinations to tests in https://github.com/hapijs/subtext/pull/17, now getting 100% coverage.

**Comment by johnbrett** [comment]
Out of interest - is it possible to monkey patch the file APIs without modify lib/index.js? I can't see any way to access the internals because of the way we create the object.

**Comment by hueniverse** [comment]
Which file API?

**Comment by johnbrett** [comment]
either:
 `internals.Parser.prototype.writeFile` https://github.com/hapijs/subtext/blob/master/lib/index.js#L432

or the `Fs.unlink ` inside `writeFile`  here: https://github.com/hapijs/subtext/blob/master/lib/index.js#L451

**Comment by hueniverse** [comment]
You can easily monkey patch `Fs` methods. Just make sure to set the test mode to `{parallel:false}` and to put things back together before the test is done.

**Comment by johnbrett** [comment]
TIL how to monkey patch `Fs` methods, thanks :)
