### ISSUE TITLE
timeout for payload not working.

### ISSUE THREAD

**Issue by lintuxt** [hapijs/subtext#19]
Hello, I have this configuration object for Hapi.js route

```javascript
    method: 'POST',
    path: '/upload',
    handler: POSTHandlers.upload,
    config: {
        payload: {
            output: 'stream',
            parse: true,
            allow: ["multipart/form-data"],
            maxBytes: 209715200,
            timeout: 4000
        }
    }
```
I believe that in the Wreck call is the issue:
Wreck.read(part, {timeout: self.settings.timeout ... is needed.
https://github.com/hapijs/subtext/blob/master/lib/index.js#L370-L427

But also, once I get to fire the timeout error, the call to self.next(Boom ... ) is not being correctly propagated.

Am I doing something wrong?

Thank you.

**Comment by johnbrett** [comment]
Hi @lintuxt, interesting spot here. That part of the code isn't touched for file upload, if you see https://github.com/hapijs/subtext/blob/master/lib/index.js#L343-L369 this is actually the part for dealing with files, so the timeout needs to be applied to either the writeFile or Pez. Will look into this further.

**Comment by lintuxt** [comment]
Actually it depends on what kind of output in the configuration object you are using. In my case I'm using stream because I want to handle the writing to disk myself. Also be aware that even though you can handle this situation. There is another problem.  https://github.com/hapijs/hapi/issues/2825 . The next() call won't work until request has finished. Cheerz!

**Comment by johnbrett** [comment]
@lintuxt I've added the fix suggested, it just failed likely to a timing issue. I will get to that, and I also want to test how this change will affect hapi to before merging in. Will hopefully get to it before the weekend.

**Comment by lintuxt** [comment]
Thank you so much John, please let me know if you need any help!

**Comment by johnbrett** [comment]
Hoping to get to this over weekend, sorry for delay on this!

**Comment by johnbrett** [comment]
Apologies for delay on this @lintuxt, fixed via https://github.com/hapijs/subtext/pull/23
