### ISSUE TITLE
2.0.2 tag

### ISSUE THREAD

**Issue by gergoerdosi** [hapijs/subtext#20]
Version 2.0.2 is on npm, but the repository doesn't have a tag for this version.

**Comment by johnbrett** [comment]
Sorry for delay - tag created: https://github.com/hapijs/subtext/releases/tag/v2.0.2

**Comment by hueniverse** [comment]
Milestones are not set correctly. 2.0.1 is still current active while 2.0.2 was published. Both should be closed after assigning the right issues to each and theh 2.0.3 created as placeholder.
