### ISSUE TITLE
Put qs back

### ISSUE THREAD

**Issue by baldmountain** [hapijs/subtext#30]
Would it be possible to put the dependency on qs back? The reason is that querystring parses:

`report_type=spend&params%5B0%5D%5Bname%5D=campaign_id&params%5B0%5D%5Bvalue%5D=56e7317660ef2242a8301b28&params%5B1%5D%5Bname%5D=month&params%5B1%5D%5Bvalue%5D=04&params%5B2%5D%5Bname%5D=year&params%5B2%5D%5Bvalue%5D=2016`

as

`{ report_type: 'spend',
  'params[0][name]': 'campaign_id',
  'params[0][value]': '56e7317660ef2242a8301b28',
  'params[1][name]': 'month',
  'params[1][value]': '04',
  'params[2][name]': 'year',
  'params[2][value]': '2016' }`

while qs parses it like:

`{ report_type: 'spend',
  params: 
   [ { name: 'campaign_id', value: '56e7317660ef2242a8301b28' },
     { name: 'month', value: '04' },
     { name: 'year', value: '2016' } ] }`

which is expected.

**Comment by hueniverse** [comment]
Nope.https://github.com/dafortune/hapi-qs

**Comment by baldmountain** [comment]
Just curious about the rationale.

I'm a bit frustrated since I spent a couple hours figuring out why a request that worked against an old project using hapi 0.8 wouldn't work with a new one using hapi 13.4. :(

**Comment by hueniverse** [comment]
That's why we have release notes. This was clearly documented. The qs module adds overhead and is not used by everyone. It is easy enough to add on your own.

**Comment by mtharrison** [comment]
If you don't want to use a plugin, there's also a [section in the API docs](http://hapijs.com/api#requestseturlurl-striptrailingslash) for how to use Qs in your app:

```js
const Url = require('url');
const Hapi = require('hapi');
const Qs = require('qs');

const server = new Hapi.Server();
server.connection({ port: 80 });

const onRequest = function (request, reply) {

    const uri = request.raw.req.url;
    const parsed = Url.parse(uri, false);
    parsed.query = Qs.parse(parsed.query);
    request.setUrl(parsed);

    return reply.continue();
};

server.ext('onRequest', onRequest);
```

**Comment by baldmountain** [comment]
OK, we pretty much skipped over hapi 12 so I wouldn't have seen the release notes for it. :(

Thanks for the explanation. :)
