### ISSUE TITLE
error version not found: subtext@4.2.2

### ISSUE THREAD

**Issue by rramakr** [hapijs/subtext#38]
Hi, 
I am getting the following npm error when I tried to do a npm install on my project which has a dependency on hapi.js.
**NPM Debug logs:**
183565 verbose cwd /app/workspace/SNAPSHOT_BUILD_5640ed9a7a40ef992652677a
183566 error Linux 2.6.32-358.2.1.el6.x86_64
183567 error argv "node" "/usr/bin/npm" "install"
183568 error node v0.10.37
183569 error npm  v2.8.3
183570 error version not found: subtext@4.2.2
183571 error If you need help, you may report this error at:
183571 error     <https://github.com/npm/npm/issues>
183572 verbose exit [ 1, true ]
183573 verbose unbuild node_modules/@walmart/snap-base-app/node_modules/hapi
183574 info preuninstall hapi@15.1.1
183575 info uninstall hapi@15.1.1

When Checked the published versions of subText, it is showing as 4.2.1.
Can you please help me to resolve the issue.

**Comment by Marsup** [comment]
You seem to be using a private npm server, check with your team for replication issues.
