### ISSUE TITLE
Error for payloads with content-encoding that fail maxBytes test

### ISSUE THREAD

**Issue by ggoodman** [hapijs/subtext#5]
Subtext replaces the original `source` stream (which is an instance of `Request`) with an instance of `Gunzip` when `Content-Encoding: gzip` (see https://github.com/hapijs/subtext/blob/master/lib/index.js#L114).

Subtext then hands off the request to Wreck. When the payload fails the `maxBytes` test, an error event is raised and Wreck attempts to `destroy()` the request (see https://github.com/hapijs/wreck/blob/master/lib/index.js#L271). However, as noted above, the stream passed to Wreck in this case is not a request, but instead an instance of `Gunzip` that has no `destroy()` method. Disaster ensues. (See also hapijs/wreck#71)

It seems that there may be a need to distinguish the payload stream from the request object passed into Wreck or otherwise remove Wreck's assumption that it is acting on a `Request` stream.

**Comment by hueniverse** [comment]
Wouldn't just not calling `destroy()` in wreck solve it then?

**Comment by hueniverse** [comment]
The bug is in wreck. As soon as that's published I'll update the deps here and in hapi.
