### ISSUE TITLE
Need to restore req body 

### ISSUE THREAD

**Issue by JohnDMathis** [hapijs/subtext#64]
I have an auth service in front of a request handling service. Generally the auth service checks headers  and authenticates requests, attaches an internal JWT auth header, and forwards the request to the appropriate service.

In a particular scenario, our auth service needs to check the body of the request in order to determine how to route it. We are using subtext to parse the request body, but I note that it appears to be a destructive action; once parsed, it's unavailable to the downstream service.

Is there a way to peek at the request body without destroying it? I read through the code and looked at "tap", but I'm not sure if that's the right track or not.

Thanks,
John

**Comment by hueniverse** [comment]
Are you using subtext directly or via hapi? The tap interface allows you to peek at the incoming payload stream as it comes in. hapi uses it for payload authentication. You can see how hapi-auth-hawk uses it. Beyond that, I do not really support direct usage of subtext outside of hapi.

**Comment by JohnDMathis** [comment]
I'm using it directly. I'll check hapi-auth-hawk...that sounds like a similar scenario, thanks.
